# Generated by Django 3.2.7 on 2021-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsfilms',
            name='role',
            field=models.CharField(choices=[('a', 'Актер'), ('w', 'Сценарист'), ('d', 'Режиссер')], max_length=1, verbose_name='Роль'),
        ),
    ]
