# Generated by Django 3.2.6 on 2021-08-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='actor',
            field=models.ManyToManyField(related_name='actors', through='main_app.ActorsFilms', to='main_app.Film', verbose_name='Актер'),
        ),
        migrations.AddField(
            model_name='person',
            name='director',
            field=models.ManyToManyField(related_name='directors', through='main_app.DirectorsFilms', to='main_app.Film', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='person',
            name='writer',
            field=models.ManyToManyField(related_name='writers', through='main_app.WritersFilms', to='main_app.Film', verbose_name='Сценарист'),
        ),
    ]
