# Generated by Django 3.2.6 on 2021-08-30 07:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('plot', models.TextField(blank=True, verbose_name='Описание')),
                ('creation_date', models.DateField(blank=True, verbose_name='Год выпуска')),
                ('certificate', models.TextField(blank=True, verbose_name='Сертификат')),
                ('file_path', models.FileField(blank=True, upload_to='films/', verbose_name='Файл')),
                ('rating', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('type', models.CharField(choices=[('mo', 'Фильм'), ('tv', 'Сериал')], default='mo', max_length=2, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Кинопроизведение',
                'verbose_name_plural': 'Кинопроизведения',
                'db_table': 'movies',
            },
            bases=(main_app.models.TimeStampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genres',
            },
            bases=(main_app.models.TimeStampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=127, verbose_name='Имя')),
                ('actor', models.ManyToManyField(related_name='actors', to='main_app.Film', verbose_name='Актер')),
                ('director', models.ManyToManyField(related_name='directors', to='main_app.Film', verbose_name='Режиссер')),
                ('writer', models.ManyToManyField(related_name='writers', to='main_app.Film', verbose_name='Сценарист')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'db_table': 'persons',
            },
            bases=(main_app.models.TimeStampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WritersFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person')),
            ],
            options={
                'db_table': 'writers_movies',
            },
        ),
        migrations.CreateModel(
            name='GenresFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.film')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.genre')),
            ],
            options={
                'db_table': 'genres_movies',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(through='main_app.GenresFilms', to='main_app.Genre'),
        ),
        migrations.CreateModel(
            name='DirectorsFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person')),
            ],
            options={
                'db_table': 'directors_movies',
            },
        ),
        migrations.CreateModel(
            name='ActorsFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person')),
            ],
            options={
                'db_table': 'actors_movies',
            },
        ),
    ]
